//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerGame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SummerGame.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран тип брони.
        /// </summary>
        internal static string EmptyArmor {
            get {
                return ResourceManager.GetString("EmptyArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран калибр.
        /// </summary>
        internal static string EmptyCaliber {
            get {
                return ResourceManager.GetString("EmptyCaliber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ничего не нарисовали.
        /// </summary>
        internal static string EmptyClickedPoints {
            get {
                return ResourceManager.GetString("EmptyClickedPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задано количество техники.
        /// </summary>
        internal static string EmptyCount {
            get {
                return ResourceManager.GetString("EmptyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрана страна.
        /// </summary>
        internal static string EmptyCountry {
            get {
                return ResourceManager.GetString("EmptyCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задано количество экипажа.
        /// </summary>
        internal static string EmptyCrew {
            get {
                return ResourceManager.GetString("EmptyCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнено поле &quot;Опыт&quot;.
        /// </summary>
        internal static string EmptyExperience {
            get {
                return ResourceManager.GetString("EmptyExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не все поля заполнены.
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задана скорострельность оружия.
        /// </summary>
        internal static string EmptyFireRate {
            get {
                return ResourceManager.GetString("EmptyFireRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введено значение для высоты.
        /// </summary>
        internal static string EmptyHeightField {
            get {
                return ResourceManager.GetString("EmptyHeightField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не ввели имя для карты.
        /// </summary>
        internal static string EmptyMapName {
            get {
                return ResourceManager.GetString("EmptyMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задана максимальная скорость движения.
        /// </summary>
        internal static string EmptyMovementSpeed {
            get {
                return ResourceManager.GetString("EmptyMovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнено поле &quot;Квалификация&quot;.
        /// </summary>
        internal static string EmptyQualification {
            get {
                return ResourceManager.GetString("EmptyQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнено поле &quot;Звание&quot;.
        /// </summary>
        internal static string EmptyRank {
            get {
                return ResourceManager.GetString("EmptyRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрана сторона.
        /// </summary>
        internal static string EmptySide {
            get {
                return ResourceManager.GetString("EmptySide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнено поле &quot;Специализация&quot;.
        /// </summary>
        internal static string EmptySpecialization {
            get {
                return ResourceManager.GetString("EmptySpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не задана численность.
        /// </summary>
        internal static string EmptyStrength {
            get {
                return ResourceManager.GetString("EmptyStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран тип войска.
        /// </summary>
        internal static string EmptyUnit {
            get {
                return ResourceManager.GetString("EmptyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнено поле &quot;Здоровье&quot;.
        /// </summary>
        internal static string EmptyVitality {
            get {
                return ResourceManager.GetString("EmptyVitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введено значение для ширины.
        /// </summary>
        internal static string EmptyWidthField {
            get {
                return ResourceManager.GetString("EmptyWidthField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле может содержать только цифры.
        /// </summary>
        internal static string FieldContainsNumbers {
            get {
                return ResourceManager.GetString("FieldContainsNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предмет успешно создан.
        /// </summary>
        internal static string GoodIsCreated {
            get {
                return ResourceManager.GetString("GoodIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отряд успешно создан.
        /// </summary>
        internal static string GroupIsCreated {
            get {
                return ResourceManager.GetString("GroupIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно введено количество.
        /// </summary>
        internal static string IncorrectGoodCount {
            get {
                return ResourceManager.GetString("IncorrectGoodCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно введено значение для высоты.
        /// </summary>
        internal static string IncorrectHeight {
            get {
                return ResourceManager.GetString("IncorrectHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный ввод.
        /// </summary>
        internal static string IncorrectInput {
            get {
                return ResourceManager.GetString("IncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поля: Максимальная скорость движения, Скорострельность оружия, Количество экипажа, Количество данного типа техники - могут содержать только цифры.
        /// </summary>
        internal static string IncorrectTextBoxValue {
            get {
                return ResourceManager.GetString("IncorrectTextBoxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно введена численность.
        /// </summary>
        internal static string IncorrectUnitCountValue {
            get {
                return ResourceManager.GetString("IncorrectUnitCountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно введено значение для ширины.
        /// </summary>
        internal static string IncorrectWidth {
            get {
                return ResourceManager.GetString("IncorrectWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оружие успешно создано.
        /// </summary>
        internal static string ItemIsCreated {
            get {
                return ResourceManager.GetString("ItemIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа или предметы не были созданы.
        /// </summary>
        internal static string ItemOrGroupIsNotCreated {
            get {
                return ResourceManager.GetString("ItemOrGroupIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при загрузке файла.
        /// </summary>
        internal static string LoadFileError {
            get {
                return ResourceManager.GetString("LoadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрана карта.
        /// </summary>
        internal static string MapIsNotChosen {
            get {
                return ResourceManager.GetString("MapIsNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение войска не выбрано.
        /// </summary>
        internal static string PositionIsNotChosen {
            get {
                return ResourceManager.GetString("PositionIsNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно нарисовать местность, так как она задана самопересекающимся многоугольником.
        /// </summary>
        internal static string SelfIntersection {
            get {
                return ResourceManager.GetString("SelfIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно нарисовать местность, так как она задана самопересекающейся ломаной.
        /// </summary>
        internal static string SelfIntersectionPolyline {
            get {
                return ResourceManager.GetString("SelfIntersectionPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войско успешно создано.
        /// </summary>
        internal static string UnitIsCreated {
            get {
                return ResourceManager.GetString("UnitIsCreated", resourceCulture);
            }
        }
    }
}
